version: "3.8"

services:

  configserver:
    image: vikkidoc/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - kaivikki
     
  eurekaserver:
    image: vikkidoc/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - kaivikki
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
  accounts:
    image: vikkidoc/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - kaivikki
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  
  loans:
    image: vikkidoc/loans:latest
    mem_limit: 700m
    ports:
      - "7000:7000"
    networks:
      - kaivikki
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  cards:
    image: vikkidoc/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - kaivikki
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
networks:
  kaivikki: